User.create(email: 'sfaisal2007@yahoo.com', first_name: 'Olivia', last_name: 'Luey', password: 'password', password_confirmation: 'password')
User.create(email: 'bollinger.ohana@gmail.com', first_name: 'Brooklyn', last_name: 'Bollinger', password: 'password', password_confirmation: 'password')
User.create(email: 'hi@regandaniels.com', first_name: 'Julia', last_name: 'Qaqundah', password: 'password', password_confirmation: 'password')
User.create(email: 'marcy.l.lim@gmail.com', first_name: 'Maddy', last_name: 'Ho', password: 'password', password_confirmation: 'password')
User.create(email: 'carol@comebuyusa.com', first_name: 'Clare', last_name: 'Wang', password: 'password', password_confirmation: 'password')
User.create(email: 'campme00@hotmail.com', first_name: 'Samantha', last_name: 'Hegel', password: 'password', password_confirmation: 'password')
User.create(email: 'kanoti.kim@gmail.com', first_name: 'Maddy', last_name: 'Kim', password: 'password', password_confirmation: 'password')
User.create(email: 'kristine.d.kirby@gmail.com', first_name: 'Kaylani', last_name: 'Kirby', password: 'password', password_confirmation: 'password')
User.create(email: 'chrisbrobertson@gmail.com', first_name: 'Catey', last_name: 'Robertson', password: 'password', password_confirmation: 'password')
User.create(email: 'letitiachan@yahoo.com', first_name: 'Sofia', last_name: 'Peypoch', password: 'password', password_confirmation: 'password')
User.create(email: 'kierstenmahon@mac.com', first_name: 'Hadley', last_name: 'Mahon', password: 'password', password_confirmation: 'password')
User.create(email: 'liongitau@gmail.com', first_name: 'Malianna', last_name: 'Liongitau', password: 'password', password_confirmation: 'password')
User.create(email: 'twschaumkel@gmail.com', first_name: 'Ella', last_name: 'Schaumkel', password: 'password', password_confirmation: 'password')

User.create(email: '_ghost_player1@mail.com', first_name: 'ghost_player1', last_name: '-', password: 'password', password_confirmation: 'password', is_ghost_player: true)
User.create(email: '_ghost_player2@mail.com', first_name: 'ghost_player2', last_name: '-', password: 'password', password_confirmation: 'password', is_ghost_player: true)
User.create(email: '_ghost_player3@mail.com', first_name: 'ghost_player3', last_name: '-', password: 'password', password_confirmation: 'password', is_ghost_player: true)
puts "== Created #{User.count} users. ===================="
