User.create(email: 'john@example.com', first_name: 'john', password: 'password', password_confirmation: 'password')
User.create(email: 'dave@example.com', first_name: 'dave', password: 'password', password_confirmation: 'password')
User.create(email: 'bill@example.com', first_name: 'bill', password: 'password', password_confirmation: 'password')
User.create(email: 'sam@example.com', first_name: 'sam', password: 'password', password_confirmation: 'password')
User.create(email: 'mike@example.com', first_name: 'mike', password: 'password', password_confirmation: 'password')
User.create(email: 'chris@example.com', first_name: 'chris', password: 'password', password_confirmation: 'password')
User.create(email: 'steve@example.com', first_name: 'steve', password: 'password', password_confirmation: 'password')
User.create(email: 'amber@example.com', first_name: 'amber', password: 'password', password_confirmation: 'password')
User.create(email: 'ginger@example.com', first_name: 'ginger', password: 'password', password_confirmation: 'password')
User.create(email: 'leo@example.com', first_name: 'leo', password: 'password', password_confirmation: 'password')
puts "== Created #{User.count} users. ===================="
