User.create(email: 'john@example.com', first_name: 'john', last_name: 'smith', password: 'password', password_confirmation: 'password')
User.create(email: 'dave@example.com', first_name: 'david', last_name: 'roth', password: 'password', password_confirmation: 'password')
User.create(email: 'bill@example.com', first_name: 'bill', last_name: 'pullman', password: 'password', password_confirmation: 'password')
User.create(email: 'sam@example.com', first_name: 'sam', last_name: 'malone', password: 'password', password_confirmation: 'password')
User.create(email: 'mike@example.com', first_name: 'mike', last_name: 'schmidt', password: 'password', password_confirmation: 'password')
User.create(email: 'chris@example.com', first_name: 'chris', last_name: 'hemsworth', password: 'password', password_confirmation: 'password')
User.create(email: 'steve@example.com', first_name: 'steve', last_name: 'jobs', password: 'password', password_confirmation: 'password')
User.create(email: 'amber@example.com', first_name: 'amber', last_name: 'lynn', password: 'password', password_confirmation: 'password')
User.create(email: 'ginger@example.com', first_name: 'ginger', last_name: 'robbins', password: 'password', password_confirmation: 'password')
User.create(email: 'leo@example.com', first_name: 'leo', last_name: 'gold', password: 'password', password_confirmation: 'password')
puts "== Created #{User.count} users. ===================="
